name: Deploy to Render

on:
  push:
    branches:
      - dev-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'  

    - name: Install dependencies
      run: |
        cd api  
        npm install 

    - name: Build the project
      run: |
        cd api  
        npm run build  

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  
        DATABASE_URL: ${{ secrets.DATABASE_URL }}  
        JWT_SECRET: ${{ secrets.JWT_SECRET }}  
      run: |
        cd api  # Asegúrate de estar en el directorio de la API
        response=$(curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "serviceId": "dpg-csc7sdogph6c73bnnvt0-a",  
            "clearCache": true
          }' \
          https://api.render.com/v1/services/dpg-csc7sdogph6c73bnnvt0-a/deploys)
        echo "Response: $response"  
